exec-once = fcitx5
exec-once = hyprpaper 
exec-once = swww-daemon
exec-once = quickshell 
exec-once = xmodmap -e "keycode 66 = Escape"
exec-once = udiskie --automount --notify
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = kded5
exec-once = kdeconnectd
