-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144",
    position = "0x0",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "rofi"
local eww         = "/home/giapwibu/eww/target/release/eww"
local screenshoot = "grim - | wl-copy"
local screenshoot1 = "grim -g \"$(slurp)\" - | wl-copy"
local wallpaper   = "~/dotfiles/wallpaper/random_wallpaper.sh"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function () 
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("xmodmap -e \"keycode 66 = Escape\"")
    hl.exec_cmd("udiskie --automount --notify")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("kded5")
    hl.exec_cmd("kdeconnectd")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "30")
hl.env("HYPRCURSOR_SIZE", "30")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 2,
        gaps_out = 4,

        border_size = 0,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 0 },
            inactive_border = "rgba(595959aa)",
        },

        resize_on_border = false,
        layout = "dwindle",
    },

    decoration = {
        rounding       = 6,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = false,
            range        = 15,
            render_power = 2,
            color        = 0xff000000,
        },

        blur = {
            enabled   = true,
            size      = 2,
            passes    = 1,
            vibrancy  = 0.0696,
        },
    },

    animations = {
        enabled = true,
    },
    
})

-- Smooth & responsive
hl.curve("smooth", {
    type = "bezier",
    points = {
        { 0.22, 1.00 },
        { 0.36, 1.00 },
    }
})

-- Fast start, soft stop
hl.curve("smoothOut", {
    type = "bezier",
    points = {
        { 0.16, 1.00 },
        { 0.30, 1.00 },
    }
})

-- Very fast UI interaction
hl.curve("quick", {
    type = "bezier",
    points = {
        { 0.25, 0.00 },
        { 0.35, 1.00 },
    }
})

-- Slight overshoot, gives a premium feel
hl.curve("pop", {
    type = "bezier",
    points = {
        { 0.20, 0.90 },
        { 0.25, 1.08 },
    }
})

-- ╭──────────────────────────────────────────────╮
-- │                  WINDOWS                     │
-- ╰──────────────────────────────────────────────╯

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4,
    bezier = "smooth",
    style = "slide",
})

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4,
    bezier = "smooth",
    style = "popin 92%",
})

hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 3,
    bezier = "quick",
    style = "popin 92%",
})

hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4,
    bezier = "smooth",
})

-- ╭──────────────────────────────────────────────╮
-- │                 WORKSPACES                   │
-- ╰──────────────────────────────────────────────╯

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "slidefade 15%",
})

hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "slidefade 15%",
})

hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 4,
    bezier = "quick",
    style = "slidefade 15%",
})

-- ╭──────────────────────────────────────────────╮
-- │                    FADE                      │
-- ╰──────────────────────────────────────────────╯

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 4,
    bezier = "smooth",
})

hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 3,
    bezier = "smoothOut",
})

hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 3,
    bezier = "quick",
})

hl.animation({
    leaf = "fadeSwitch",
    enabled = true,
    speed = 3,
    bezier = "smoothOut",
})

-- ╭──────────────────────────────────────────────╮
-- │                   LAYERS                     │
-- ╰──────────────────────────────────────────────╯

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 4,
    bezier = "smooth",
    style = "slide",
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "smooth",
    style = "slide",
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 3,
    bezier = "quick",
    style = "slide",
})

-- ╭──────────────────────────────────────────────╮
-- │               SPECIAL WORKSPACE              │
-- ╰──────────────────────────────────────────────╯

hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "slidefade 15%",
})

hl.animation({
    leaf = "specialWorkspaceIn",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "slidefade 15%",
})

hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 4,
    bezier = "quick",
    style = "slidefade 15%",
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
    misc = {
        disable_hyprland_logo = true,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "caps:swapescape, altwin:alt_super_win",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0.5,

        touchpad = {
            natural_scroll = true,
            scroll_factor = 0.4,
        },
    },
    -- gestures = {
    --     workspace_swipe = false,
    -- },
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + U", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("echo open > /tmp/.qs-launcher.fifo"))
hl.bind(mainMod .. " + I", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("~/.config/rofi/wifi-menu.sh"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("~/.dotfiles/wallpapers/next_wallpaper.sh"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("~/.dotfiles/wallpapers/prev_wallpaper.sh"))

hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(screenshoot))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd(screenshoot1))

hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + h", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.focus({ direction = "down" }))

for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + M",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(wallpaper))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.layer_rule({
    match = { namespace = "quickshell-pill" },
    blur = true,
    ignore_alpha = 0.2,
})
