# BACKGROUND
background {
    monitor =
    #blur_size = 5
    #blur_passes = 4
    path = ~/.dotfiles/wallpapers/background.jpg

}

general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %d %b")"
  color = rgba(255, 255, 255, 0.9)
  font_size = 60
  font_family = Hack Nerd Font, bold 
  position = 0, 375
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%H")"
  color = rgba(172, 166, 180, 1)
  font_size = 300
  font_family = Adwaita Sans, Heavy
  position = -650, 340
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%M")"
  color = rgba(255, 255, 255, 1)
  font_size = 280
  font_family = Adwaita Sans, Heavy
  position = -300, 180
  halign = center
  valign = center
}

background {
    monitor =
    zindex = 1
    keep_aspect_ratio = true
    rounding = 0
    border_size = 0
    path = ~/.dotfiles/wallpapers/background_remove.png
}

