unbind r
bind r source ~/.tmux.conf

set -g prefix C-s
set -g mouse on

set -g base-index 1
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g status-position bottom
set -g mouse on
set -g escape-time 0
set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",xterm-kitty:Tc"
set -g default-command "fish" 

set -g status-style "bg=black,fg=#eeeeee"
set -g status-interval 1
set -g status-left-length 200
set -g status-left "#\[bg=#121212 fg=white\]  | #\[fg=white\] #S  #\[bg=#ffffff fg=#121212\]#\[fg=black\]  #(basename #{pane\_current\_path}) #\[bg=black fg=#ffffff\]"
set -g status-right "#\[bg=black fg=#ffffff\]#\[bg=#ffffff fg=black\]  %H:%M #\[bg=#ffffff fg=#121212\]#\[bg=#121212 fg=white\]  %D"
set -g status-justify "absolute-centre"
set -g window-status-current-format "#\[bg=black fg=#ffffff\]#\[bg=#ffffff,fg=#000000\] #I #W #F #\[bg=black,fg=#ffffff\]"
set -g window-status-format "#\[bg=black fg=#121212\]#\[bg=#121212,fg=white\] #I #W #F #\[bg=black,fg=#121212\]"
set -g pane-active-border-style "fg=white"
set -g pane-border-style "fg=white"
set -g message-style "bg=black,fg=white"
set -g mode-style "bg=#b5befe,fg=#11111b"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'
